<div class="col-xs-12">
    <fieldset>
        <legend>การขนส่ง</legend>
        <form>
            <div class="row">
                <div class="col-xs-1">
                    <label>Package</label>
                </div>
                <div class="col-xs-2">
                    <select class="form-control"></select>
                </div>
                <div class="col-xs-1">
                    <label>ประเภท</label>
                </div>
                <div class="col-xs-2">
                    <select class="form-control"></select>
                </div>
                <div class="col-xs-2">
                    <label>ทุนประกันภัย</label>
                </div>
                <div class="col-xs-2">
                    <select class="form-control"></select>
                </div>
                <div class="col-xs-2">
                </div>
            </div>
            <div class="row">

            </div>
            <div class="row">
                <div class="col-xs-12">
                    <button class="btn btn-default">ซื้อประกันภัย</button>
                </div>
            </div>
        </form>
    </fieldset>
</div>