<div class="col-xs-12" ng-controller="motorMainCtrl" ng-init="init()">
    <form>
        <fieldset>
            <legend>รถยนประเภท {{type}}</legend>
        <div class="row">
            <div class="col-xs-1">
                <label>Brand</label>
            </div>
            <div class="col-xs-2">
                <select class="form-control" ng-model="model.brand.id" ng-change="brandChange(model.brand.id)">
                    <option value="0"></option>
                    <option ng-repeat="item in brands" value="{{item.id}}" ng-selected="item.id==model.brand.id">
                        {{item.name}}
                    </option>
                </select>
            </div>
            <div class="col-xs-1">
                  <label>Model</label>
            </div>
            <div class="col-xs-2">
                <select class="form-control" ng-model="model.model.id">
                    <option value="0"></option>
                    <option ng-repeat="item in models" value="{{item.id}}" ng-selected="item.id==model.model.id">{{item.name}}</option>
                </select>
            </div>
            <div class="col-xs-1">
                    <label>Year</label>
            </div>
            <div class="col-xs-2">
                   <input kendo-numeric-text-box style="width:100%"/>
            </div>
            <div class="col-xs-3">
               
            </div>
        </div>
            <div class="row">
                <div class="col-xs-12">
                    
                     <button class="btn btn-default" ng-click="buyMotor()">ซื้อประกัน</button>
                </div>
            </div>
       </fieldset>
    </form>
</div>








  








 





   



</div>