<div class="modal-header">
    <h3 class="modal-title">ซื้อประกันภัยรถยนต์</h3>
</div>
<div class="modal-body col-xs-12" ng-init="init()">
    <form>
        <ul class="nav nav-tabs">
            <li class="active"><a href="#policy" data-toggle="tab">Policy</a></li>
            <li><a href="#shipping" data-toggle="tab">Shipping</a></li>
            <li><a href="#confirm" data-toggle="tab">confirm</a></li>
            <li><a href="#payment" data-toggle="tab">Payment</a></li>
        </ul>
        <div class="tab-content">
            <div id="policy" class="tab-pane fade in active">

                <?php $this->partial("motor/policy"); ?>
            </div>
            <div id="shipping" class="tab-pane fade">
                 <?php $this->partial("motor/shipping"); ?>   

            </div>
           <div id="confirm" class="tab-pane fade">
                <?php $this->partial("motor/confirm"); ?>  

            </div>
            <div id="payment" class="tab-pane fade">
                <?php $this->partial("motor/payment"); ?>  

            </div>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button class="btn btn-default" type="button" ng-click="save()">Save</button>
    <button class="btn btn-default" type="button" ng-click="close()">Close</button>
</div>