<div class="col-xs-12">
    <fieldset><legend>ข้อมูลลูกค้า</legend>
        <div class="row">
            <div class="col-xs-3">
                <label>คำนำหน้าชื่อ</label>
            </div>
            <div class="col-xs-9">
                <select class="form-control"></select>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>ชื่อ</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>นามสกุล</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>Birth Date</label>
            </div>
            <div class="col-xs-3">
                <input kendo-date-picker k-format="'dd/MM/yyyy'" style="width:100%"/>
            </div>
            <div class="col-xs-3">
                <label>เลขประจำตัวประชาชน</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>อาชีพ</label>
            </div>
            <div class="col-xs-9">
                <select class="form-control"></select>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>บ้านเลขที่</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>หมู่ที่</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>ซอย</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>ถนน</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>จังหวัด</label>
            </div>
            <div class="col-xs-3">
                <select class="form-control"></select>
            </div>
            <div class="col-xs-3">
                <label>อำเภอ</label>
            </div>
            <div class="col-xs-3">
                <select class="form-control"></select>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>ตำบล</label>
            </div>
            <div class="col-xs-3">
                <select class="form-control"></select>
            </div>
            <div class="col-xs-3">
                <label>รหัสไปรษณีย์</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>เบอร์มือถือ</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>เบอร์บ้าน</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>โทรสาร</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>Email</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend>กรมธรรม์</legend>
        <div class="row">
            <div class="col-xs-3">
                <label>วันที่เริ่มคุ้มครอง</label>
            </div>
            <div class="col-xs-3">
                <input kendo-date-picker k-format="'dd/MM/yyyy'" style="width:100%"/>
            </div>
            <div class="col-xs-3">
                <label>ประเภทกรมธรรม์</label>
            </div>
            <div class="col-xs-3">

            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>ยี่ห้อ</label>
            </div>
            <div class="col-xs-3">

            </div>
            <div class="col-xs-3">
                <label>รุ่น</label>
            </div>
            <div class="col-xs-3">

            </div>
        </div>

        <div class="row">
            <div class="col-xs-3">
                <label>เลขเครื่อง</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>เลขตัวถัง</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>ผู้ขับขี่ 1</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>ผู้ขับขี่ 2</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>เลขที่ใบขับขี่ 1</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>เลขที่ใบขับขี่  2</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-3">
                <label>ทะเบียนรถ</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>จังหวัด</label>
            </div>
            <div class="col-xs-3">
                <select class="form-control"></select>
            </div>
        </div>
        <div class="row">
               <div class="col-xs-3">
                <label>ปีรถ</label>
            </div>
            <div class="col-xs-3">
                
            </div>
            <div class="col-xs-3">
                <label>ทุนประกัน</label>
            </div>
            <div class="col-xs-3">
                
            </div>
        </div>
    </fieldset>
</div>