<div class="col-xs-12">
    <div class="row">
        <div class="col-xs-3">
            <label>คำนำหน้าชื่อ</label>
        </div>
        <div class="col-xs-9">
            <select class="form-control"></select>
        </div>
      
    </div>
    <div class="row">
        <div class="col-xs-3">
            <label>ชื่อผู้จัดส่ง</label>
        </div>
        <div class="col-xs-3">
            <input type="text" class="form-control"/>
        </div>
          <div class="col-xs-3">
            <label>นามสกุล</label>
        </div>
        <div class="col-xs-3">
            <input type="text" class="form-control"/>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-3">ประเภทการจัดส่ง</div>
        <div class="col-xs-9">
            <div class="radio-inline">
                <input type="radio" name="shippingType" value="A"/>Ems
            </div>
            <div class="radio-inline">
                <input type="radio" name="shippingType" value="B"/>Normal
            </div>
        </div>
    </div>
     <div class="row">
            <div class="col-xs-3">
                <label>บ้านเลขที่</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>หมู่ที่</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>ซอย</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>ถนน</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>จังหวัด</label>
            </div>
            <div class="col-xs-3">
                <select class="form-control"></select>
            </div>
            <div class="col-xs-3">
                <label>อำเภอ</label>
            </div>
            <div class="col-xs-3">
                <select class="form-control"></select>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>ตำบล</label>
            </div>
            <div class="col-xs-3">
                <select class="form-control"></select>
            </div>
            <div class="col-xs-3">
                <label>รหัสไปรษณีย์</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>เบอร์มือถือ</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>เบอร์บ้าน</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3">
                <label>โทรสาร</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
            <div class="col-xs-3">
                <label>Email</label>
            </div>
            <div class="col-xs-3">
                <input type="text" class="form-control"/>
            </div>
        </div>
</div>